#!/usr/bin/env bash

# Custom https header

# Update package repositories and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Check if Nginx installation was successful
if [ $? -ne 0 ]; then
    echo "Nginx installation failed. Exiting."
    exit 1
fi

# Configure firewall to allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create directory for web content
sudo mkdir -p /var/www/html

# Set permissions for web directory
sudo chmod -R 755 /var/www

# Create index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to include custom header and redirect
sudo sed -i.bak '/server_name _;/a \ \n\tadd_header X-Served-By $(hostname);' /etc/nginx/sites-enabled/default
sudo sed -i.bak 's/#error_page 404 \/404.html;/error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

