#!/usr/bin/env bash
# Configure Nginx servers (on web-01 and 02)such that contain custom HTTP response header
# name of the header: X-Served-By
# value: hostname
sudo apt-get update
sudo apt-get -y install nginx

# allow firewall for nginx requests through :80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# grant permissions
sudo chmod -R 755 /var/www

#  create index html page
echo 'Welcome to my server!' |sudo tee  /var/www/html/index.html

# create error html page
echo "This page does not exist" |sudo tee /var/www/html/404.html

# redirect and display hostname
replace="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

# redirect to 404 error html page
replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-enabled/default

# restart web server
sudo service nginx restart
