#!/usr/bin/env bash
# This bash script installs and initializes HAProxy on lb-01 server
# sets HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests by roundrobin algorithm
# allow to manage HAProxy via an init script

# Install and set HAProxy
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 145450-web-01 100.25.19.204:80 check
        server 145450-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
