#!/usr/bin/env bash
# backup and archive my database

# archive variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

# dump

sudo mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
