#!/usr/bin/env bash
# This is a bash script
# What it does:
# Creates the file /var/run/myscript.pid containing its own PID
# Displays To 'infinity and beyond indefinitely'
# Displays 'I hate the kill command when receiving a SIGTERM signal'
# Displays 'Y U no love me?!' when interupted by a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminate when
# interupted by SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done
