#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely with 2 seconds
# intervals between each iteration and 'I am invincible' in between

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
