#!/usr/bin/env bash
# This script loops through 1 to 10 using while loop
# and adds some features with if and elif

i=0

while [ $i -le 9 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
