#!/usr/bin/env bash
# debug docker issues
# apache must display Hello holberton when queried

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start

# display index file

echo "Hello Holberton" | sudo tee -a /var/www/html/index.html

# Restart apache server

sudo /etc/init.d/apache2 restart
