#!/usr/bin/env bash
# change nginx user to nginx instead of root
# and listen to port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
